---
title: "Individual"
author: "Jyotishka"
output:
  pdf_document:
    keep_tex: true
  html_document:
    df_print: paged
fontsize: 14pt
geometry: margin=0.9in
mainfont: cochineal
fontfamily: libertine
sansfont: Linux Biolinum O
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)
library(kableExtra)
library(tinytex)
library(rio)

source('~/R/R Codes/Experiments with R/Temp-BStat/Demography/Group Project/Complete-Life-Table.R')

ALT_States <- import_list("D:/My Documents/R/R Codes/Experiments with R/Temp-BStat/Demography/Individual Project/ALT_States_01_05.xlsx")

Census_2001 <- import_list("D:/My Documents/R/R Codes/Experiments with R/Temp-BStat/Demography/Individual Project/Census_2001.xlsx")

states <- ALT_States %>% names()
```



\pagebreak
# India

```{r, echo=FALSE}

options(scipen = 999)

#################### State
k <- 1
J <- complete.LT(ALT_States[[k]])
   
   ##### Total (Row 1)
   h <- 1
   caption <- paste0(states[k], " : Total Migration")
   J.h <- cbind(J[[h]][[1]],J[[h]][[2]],J[[h]][[3]])
   colnames(J.h) <- rep(c("q\\textsubscript{x}","l\\textsubscript{x}",
                  "L\\textsubscript{x}","e\\textsubscript{x}"),3)
   
   S <- list()
   
   for(i in 1:3){
      S[[i]] <- as.numeric(sapply(1:76, function(val){
         return(J[[h]][[i]]$L_x[val+10] / J[[h]][[i]]$L_x[val])
      }))
   }
   
   net.M <- list()
   
   for(i in 1:3){
      net.M[[i]] <- as.numeric(Census_2001[[1]][[i+6]][2:77] #####
                               - S[[i]] * Census_2001[[1]][[i+6]][2:77])
   }
   
   mt <- list()
   
   for(i in 1:3){
      mt[[i]] <- data.frame("S_x" = S[[i]],
                            "P_2001" = Census_2001[[1]][[i+6]][2:77],
                            "P_2011" = Census_2001[[1]][[i+6]][2:77], #####
                            "net.M" = net.M[[i]])
   }
   
   mt <- cbind(mt[[1]],mt[[2]],mt[[3]])
   
   rownames(mt) <- 0:75
   colnames(mt) <- rep(c("S\\textsubscript{x}","P\\textsubscript{2001}",
                         "P\\textsubscript{2011}","Net.M"),3)
   
   kbl(mt, longtable = TRUE, booktabs = TRUE, caption = caption, 
          format = "latex", escape = F, align = rep("c",12)) %>%
         add_header_above(c(" ", "Total" = 4, "Male" = 4, "Female" = 4)) %>%
         kable_styling(latex_options = c("repeat_header"))
   
   
   ##### Rural (Row 2)
   h <- 2
   caption <- paste0(states[k], " : Rural Migration")
   J.h <- cbind(J[[h]][[1]],J[[h]][[2]],J[[h]][[3]])
   colnames(J.h) <- rep(c("q\\textsubscript{x}","l\\textsubscript{x}",
                  "L\\textsubscript{x}","e\\textsubscript{x}"),3)
   
   S <- list()
   
   for(i in 1:3){
      S[[i]] <- as.numeric(sapply(1:76, function(val){
         return(J[[h]][[i]]$L_x[val+10] / J[[h]][[i]]$L_x[val])
      }))
   }
   
   net.M <- list()
   
   for(i in 1:3){
      net.M[[i]] <- as.numeric(Census_2001[[1]][[i+9]][2:77] #####
                               - S[[i]] * Census_2001[[1]][[i+9]][2:77])
   }
   
   mt <- list()
   
   for(i in 1:3){
      mt[[i]] <- data.frame("S_x" = S[[i]],
                            "P_2001" = Census_2001[[1]][[i+9]][2:77],
                            "P_2011" = Census_2001[[1]][[i+9]][2:77], #####
                            "net.M" = net.M[[i]])
   }
   
   mt <- cbind(mt[[1]],mt[[2]],mt[[3]])
   
   rownames(mt) <- 0:75
   colnames(mt) <- rep(c("S\\textsubscript{x}","P\\textsubscript{2001}",
                         "P\\textsubscript{2011}","Net.M"),3)
   
   kbl(mt, longtable = TRUE, booktabs = TRUE, caption = caption, 
          format = "latex", escape = F, align = rep("c",12)) %>%
         add_header_above(c(" ", "Total" = 4, "Male" = 4, "Female" = 4)) %>%
         kable_styling(latex_options = c("repeat_header"))

   
   ##### Urban (Row 3)
   h <- 3
   caption <- paste0(states[k], " : Urban Migration")
   J.h <- cbind(J[[h]][[1]],J[[h]][[2]],J[[h]][[3]])
   colnames(J.h) <- rep(c("q\\textsubscript{x}","l\\textsubscript{x}",
                  "L\\textsubscript{x}","e\\textsubscript{x}"),3)
   
   S <- list()
   
   for(i in 1:3){
      S[[i]] <- as.numeric(sapply(1:76, function(val){
         return(J[[h]][[i]]$L_x[val+10] / J[[h]][[i]]$L_x[val])
      }))
   }
   
   net.M <- list()
   
   for(i in 1:3){
      net.M[[i]] <- as.numeric(Census_2001[[1]][[i+12]][2:77] #####
                               - S[[i]] * Census_2001[[1]][[i+12]][2:77])
   }
   
   mt <- list()
   
   for(i in 1:3){
      mt[[i]] <- data.frame("S_x" = S[[i]],
                            "P_2001" = Census_2001[[1]][[i+12]][2:77],
                            "P_2011" = Census_2001[[1]][[i+12]][2:77], #####
                            "net.M" = net.M[[i]])
   }
   
   mt <- cbind(mt[[1]],mt[[2]],mt[[3]])
   
   rownames(mt) <- 0:75
   colnames(mt) <- rep(c("S\\textsubscript{x}","P\\textsubscript{2001}",
                         "P\\textsubscript{2011}","Net.M"),3)
   
   kbl(mt, longtable = TRUE, booktabs = TRUE, caption = caption, 
          format = "latex", escape = F, align = rep("c",12)) %>%
         add_header_above(c(" ", "Total" = 4, "Male" = 4, "Female" = 4)) %>%
         kable_styling(latex_options = c("repeat_header"))
```







